name: mp3yap
description: YouTube MP3 Downloader with Flutter
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0

  # HTTP & WebSocket
  dio: ^5.4.0
  web_socket_channel: ^2.4.0

  # Audio Player
  audioplayers: ^5.2.1

  # File Picker
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  path: ^1.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
